<?php

declare(strict_types=1);

namespace KrubiK\Render\Kernel;
/*
| Krubot BotEngine: The Architect's Lexicon [×vRC.8×] 🚀📜
|--------------------------------------------------------------------------
| This is **a Playground For Mastery**, a laboratory of ***Software Dev Artistry***;
| not a weapon for production's final battles.
|
| Our Bond: ***"Rebuilding The Rebellion"*** Within S.N.P. (The Foundation of Pure Power & Revel).
| Your Mandate [MIT]: Deconstruct Krubot. Command it. Master it. You are The Architect Now!
|
| *Go build something revolutionary!* 💜⚡️
*/

use Illuminate\Support\Facades\Blade;
use KrubiK\Render\Kernel\BladeCipher;  // Imported for clarity
use KrubiK\Render\Parsers\SyntaxWarden;
use RuntimeException;
use Throwable; // Import Throwable for robust error handling

/**
 * The "In-Memory Oracle" Parser - v2.0
 *
 * This parser does not parse anything itself. It's a meta-parser that leverages
 * Laravel's entire Blade compilation engine. It takes a string fragment containing
 * Blade directives, wraps it in the BladeCipher lifecycle, executes the resulting
 * PHP in a sandboxed environment, and harvests the generated RichEntity objects.
 *
 * This version providing a massive performance boost, by using a rare-known technique
 * to execute mixed PHP/HTML code from a string using eval().
 * Note! This is safe in our context as we are only executing code generated by
 * Laravel's trusted Blade compiler, not a raw user input.
 *
 * @author DoKtor K.
 * @link https://StoryKo.de/Krubot Official website of engine.
 * @version Krubot: ×RC.8×
 * @license MIT
*/
class RichBladeFragmentParser implements SyntaxWarden
{
    /**
     * Parses a string containing Blade directives by compiling and executing it entirely in-memory.
     *
     * @param string $input The string fragment, e.g., "And then @Bold()This@EndBold() happened...".
     * @return array<int, \KrubiK\Render\RichElements\RichEntity> An array of entities.
     */
    public function decipher(string $input): array
    {
        // Step 1: Compile the Blade fragment. This is fast and happens in memory.
        $compiledPhpFragment = Blade::compileString($input);

        // Step 2: Execute the entire process inside a closure to prevent variable leakage.
        // This closure will return the final array of entities.
        $result = (function() use ($compiledPhpFragment) {
            
            // Get the singleton instance of our celestial conductor.
            $builder = BladeCipher::getInstance();

            // Begin the capture process. This also starts output buffering (ob_start).
            $builder->begin();

            try {
                /**
                 * === THE HYPER-PERFORMANCE KEY ===
                 * We use eval() to execute the compiled code. The '?>' prefix is the crucial trick.
                 * It tells the PHP parser to immediately exit PHP mode and treat the following
                 * content as plain output, which is exactly how compiled Blade templates work.
                 * The output buffering started by `begin()` will capture all the plain text,
                 * and the PHP code within the fragment will call our BladeCipher methods as expected.
                 * This completely bypasses the need for a temporary file.
                 */
                eval('?>' . $compiledPhpFragment);

            } catch (Throwable $e) {
                // CRITICAL: If any error occurs during eval (syntax error, runtime exception),
                // we MUST clean up the BladeCipher's state to prevent catastrophic failure
                // on subsequent calls in the same request.
                $builder->end(); // This discards the failed run and cleans the output buffer.

                // Re-throw the exception with more context for easier debugging.
                throw new RuntimeException('Failed to execute RichBlade fragment: ' . $e->getMessage(), 0, $e);
            }

            // End the capture. This stops output buffering, captures any final text,
            // processes the stack, and returns the final, fully-formed RichMan masterpiece.
            $finalComposer = $builder->end();

            return $finalComposer ? $finalComposer->main->getElements() : [];
        })();

        return is_array($result) ? $result : [];
    }
}
