<?php

namespace KrubiK\Console;
/*
| Krubot BotEngine: The Architect's Lexicon [×vRC.8×] 🚀📜
|--------------------------------------------------------------------------
| This is **a Playground For Mastery**, a laboratory of ***Software Dev Artistry***;
| not a weapon for production's final battles.
|
| Our Bond: ***"Rebuilding The Rebellion"*** Within S.N.P. (The Foundation of Pure Power & Revel).
| Your Mandate [MIT]: Deconstruct Krubot. Command it. Master it. You are The Architect Now!
|
| *Go build something revolutionary!* 💜⚡️
*/

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use KrubiK\Krubot;
use Illuminate\Support\Str;

class CacheNexusesCommand extends Command
{
    protected $signature = 'nexus:cache';
    protected $aliases = ['krubik:nexus-cache'];
    protected $description = 'Discover and cache the full list of Nexus classes for maximum performance.';

    public function handle(Krubot $krubot): int
    {
        $this->info('🚀 Caching Nexus manifest...');

        $cachePath = config('krubot.cache.path');
        
        // Clear any old cache.
        if (File::exists($cachePath)) {
            File::delete($cachePath);
        }

        if(config('krubot.cache.opcache_enabled', true))
            opcache(null); // sending null to opcache() helper Invalidates Entire OPCache Entries (internally runs Opcache::flush())

        // We need the *full* list, so we call the boot logic manually.
        // The service provider already loaded them into the main instance.
        $nexuses = $krubot->getIntegratedNexuses();

        if (empty($nexuses)) {
            $this->warn('No Nexuses found to cache. The cache file will not be created.');
            return self::SUCCESS;
        }

        $forcePatterns = config('krubot.cache.force_refresh', []);

        if(count($forcePatterns)) {

            $basePath = base_path() . DIRECTORY_SEPARATOR;

            foreach ($nexuses as $nexusFqcn) {
                try {
                    $reflection = new \ReflectionClass($nexusFqcn);
                    $filePath = $reflection->getFileName();

                    // PHP 8.2 Type-Safety Guard:
                    // ReflectionClass::getFileName() returns string|false.
                    // Passing false to Str::after() throws TypeError in strict mode.
                    if ($filePath === false) {
                        $this->warn("Skipping evaluation of {$nexusFqcn}: File path is not resolvable.");
                        continue;
                    }

                    // We need the relative path to match config patterns and correct comparison, as they defined in the config.php
                    $relativePath = Str::after($filePath, $basePath);

                    if (Str::is($forcePatterns, $relativePath)) {
                        // CONFLICT FOUND! A Nexus is marked for forced refresh, so it cannot be part of a static cache.
                        $this->error('Operation Aborted: A direct conflict exists between the cache policy and the discovered classes found, in the `cache.force_refresh` configuration.');
                        $this->warn("Conflict detected at: {$relativePath}");
                        return self::FAILURE;
                    }
                } catch (\ReflectionException $e) {
                    // This class was found but couldn't be reflected. Log or warn, but continue.
                    $this->warn("Could not reflect class {$nexusFqcn} to check for conflicts. Skipping.");
                    continue;
                }
            }
        }


        // Prepare the content for the cache file.
        $content = "<?php\n\n// This file is auto-generated by the krubot:nexus-cache command.\n// Do not edit it manually!\n\nreturn " . var_export($nexuses, true) . ";\n";

        // Ensure the cache directory exists.
        File::ensureDirectoryExists(dirname($cachePath));
        File::put($cachePath, $content);

        $this->info("✅ Nexus manifest cached successfully. (" . count($nexuses) . " total)");
        return self::SUCCESS;
    }
}
